name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Verify requirements.txt exists
        run: ls -l requirements.txt || echo "requirements.txt not found!"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "❌ ERROR: requirements.txt not found!"
            exit 1
          fi

      - name: Run tests
        run: python -m unittest discover tests
